OBJS_TEST_CAUSALIZATION := $(OBJS_COMMON) \
                  util/debug.o \
                  util/table.o \
                  util/type.o \
                  util/solve/solve.o \
                  util/ast_visitors/evalexp.o \
                  util/ast_visitors/part_evalexp.o \
                  util/ast_visitors/ginac_interface.o \
                  util/ast_visitors/contains.o \
                  causalize/for_unrolling/for_index_iterator.o \
                  causalize/for_unrolling/process_for_equations.o \
                  causalize/state_variables_finder.o \
                  causalize/unknowns_collector.o \
                  causalize/causalization_strategy.o \
                  causalize/vector/contains_vector.o \
                  causalize/vector/graph_builder.o \
                  causalize/apply_tarjan.o \
                  mmo/mmo_class.o
                                                      
OBJS_TEST_TARJAN := util/debug.o \
                    causalize/apply_tarjan.o \
                    test/causalize/apply_tarjan_test.o

TEST_LIBS = -lboost_unit_test_framework -L./lib -lmodelica -lginac

test/causalize/causalization_strategy_test: $(OBJS_TEST_CAUSALIZATION) test/causalize/causalization_strategy_test.o
	$(CXX) $(CXXFLAGS) -o test/causalize/causalization_strategy_test $(OBJS_TEST_CAUSALIZATION) test/causalize/causalization_strategy_test.o $(TEST_LIBS)
      
test/causalize/apply_tarjan_test: $(OBJS_TEST_TARJAN) lib/libmodelica.a
	$(CXX) $(CXXFLAGS) -o test/causalize/apply_tarjan_test $(OBJS_TEST_TARJAN) $(TEST_LIBS)

test/causalize/performance_test: $(OBJS_TEST_CAUSALIZATION) test/causalize/performance_test.o
	$(CXX) $(CXXFLAGS) -o test/causalize/performance_test $(OBJS_TEST_CAUSALIZATION) test/causalize/performance_test.o $(TEST_LIBS)
