OBJS_CAUSALIZE_FOR_UNROLLING_TEST := $(OBJS_COMMON) \
            causalize/graph_implementation/compref_occurrence.o \
            mmo/mmo_class.o \
            util/ast_util.o \
            util/type.o \
            util/type_check.o \
            util/symbol_table.o \
            util/debug.o \
            causalize/graph_implementation/for_unrolling/for_index_iterator.o \
            causalize/graph_implementation/for_unrolling/process_for_equations.o \
            test/causalize/graph_implementation/for_unrolling/process_for_equations_test.o

LIB_CAUSALIZE_FOR_UNROLLING_TEST = -lboost_unit_test_framework

test/causalize/graph_implementation/for_unrolling/process_for_equations_test: $(OBJS_CAUSALIZE_FOR_UNROLLING_TEST)
	$(CXX) $(CXXFLAGS) -o test/causalize/graph_implementation/for_unrolling/process_for_equations_test $(OBJS_CAUSALIZE_FOR_UNROLLING_TEST) $(LIB_CAUSALIZE_FOR_UNROLLING_TEST)



	
