all: test/util/GraphTest test/util/PrintGraphs

SRC_TEST_UTIL1 := test/util/GraphTest.cpp \
    util/graph/graph_definition.cpp \
    util/graph/graph_algorithms.cpp \
    util/debug.cpp 

SRC_TEST_UTIL2 := test/util/PrintGraphs.cpp

OBJS_TEST_UTIL1= $(SRC_TEST_UTIL1:.cpp=.o)
-include $(patsubst %,$(DEPDIR)/%.d,$(basename $(SRC_TEST_UTIL1)))

OBJS_TEST_UTIL2= $(SRC_TEST_UTIL2:.cpp=.o)
-include $(patsubst %,$(DEPDIR)/%.d,$(basename $(SRC_TEST_UTIL2)))

test/util/GraphTest: $(OBJS_TEST_UTIL1)
	$(CXX) $(CXXFLAGS) -o test/util/GraphTest $(OBJS_TEST_UTIL1) $(LIB_TEST)

test/util/PrintGraphs: $(OBJS_TEST_UTIL2)
	$(CXX) $(CXXFLAGS) -o test/util/PrintGraphs $(OBJS_TEST_UTIL2) $(LIB_TEST)



	
