# The Directories, Source, Includes, Objects, Binary 
UTIL_DIR        := util
TEST_DIR        := test
GRP_TEST        := test/util/GraphTest
GRP_PRINT_TEST  := test/util/PrintGraphs
SBG_GRAPH_TEST  := test-sbg-graph

all: $(GRP_TEST) $(GRP_PRINT_TEST) 

GRP_TEST_SRC := \
    $(TEST_DIR)/util/GraphTest.cpp \
    $(UTIL_DIR)/graph/graph_definition.cpp \
    $(UTIL_DIR)/graph/graph_algorithms.cpp \
    $(UTIL_DIR)/debug.cpp 

GRP_PRINT_TEST_SRC := \
    test/util/PrintGraphs.cpp

# Objects
GRP_TEST_OBJ=$(addprefix $(BUILD_DIR)/, $(GRP_TEST_SRC:.cpp=.o))

GRP_PRINT_TEST_OBJ=$(addprefix $(BUILD_DIR)/, $(GRP_PRINT_TEST_SRC:.cpp=.o))

create-folders::
	@mkdir -p $(BUILD_DIR)/$(UTIL_DIR)/test
	@mkdir -p $(BUILD_DIR)/$(UTIL_DIR)/test/util

$(GRP_TEST): $(GRP_TEST_OBJ)
	$(CXX) $(INCLUDES) $(CXXFLAGS) -o $(GRP_TEST) $(GRP_TEST_OBJ) $(LIBS)

$(GRP_PRINT_TEST): $(GRP_PRINT_TEST_OBJ)
	$(CXX) $(INCLUDES) $(CXXFLAGS) -o $(GRP_PRINT_TEST) $(GRP_PRINT_TEST_OBJ) $(LIBS)

$(SBG_GRAPH_TEST):
	@echo RUNNING SBG GRAPHS UNIT TESTS
	@cd test/util && $(MAKE)
	@cd test/util && ./GraphTest
	@cd test/util && ./PrintGraphs 
	@echo Done
