all: bin/vg_causalize 
SRC_VG_CAUSALIZE := \
                  causalize/vg_implementation/main.cpp \
                  causalize/vg_implementation/apply_tarjan.cpp \
                  causalize/vg_implementation/unknowns_collector.cpp \
                  causalize/vg_implementation/causalization_strategy.cpp \
                  causalize/vg_implementation/vector/graph_builder.cpp \
                  causalize/vg_implementation/vector/causalization_algorithm.cpp \
                  causalize/vg_implementation/vector/splitfor.cpp \
                  causalize/vg_implementation/vector/vector_graph_definition.cpp \
                  causalize/vg_implementation/vector/vector_tarjan.cpp \
                  causalize/vg_implementation/vector/vector_matching.cpp \
                  causalize/vg_implementation/graph/graph_definition.cpp \
                  causalize/vg_implementation/for_unrolling/process_for_equations.cpp \
                  util/ast_visitors/contains_unknown.cpp \
                  util/ast_visitors/contains_vector.cpp \


OBJS_VG_CAUSALIZE = $(SRC_VG_CAUSALIZE:.cpp=.o)
-include $(patsubst %,$(DEPDIR)/%.d,$(basename $(SRC_VG_CAUSALIZE)))
LIB_CAUSALIZE = -L./lib -lmodelica -lginac

bin/vg_causalize: $(OBJS_COMMON_CAUSALIZE) $(OBJS_VG_CAUSALIZE) lib/libmodelica.a
	$(CXX) $(CXXFLAGS) -o bin/vg_causalize $(OBJS_COMMON_CAUSALIZE) $(OBJS_VG_CAUSALIZE) $(LIB_CAUSALIZE)
