OBJS_EXPANDFOR := expandfor/main.o \
	mmo/mmo_class.o \
	util/table.o \
	util/type.o \
	util/debug.o \
	util/ast_visitors/evalexp.o \
	util/ast_visitors/part_evalexp.o \
	util/ast_visitors/expandfor_visitor.o \
	expandfor/expandfor.o
LIBS=-L./lib -lginac -lmodelica 
bin/expandfor: $(OBJS_EXPANDFOR) lib/libmodelica.a
	$(CXX) $(CXXFLAGS) $(OBJS_EXPANDFOR) -o bin/expandfor $(LIBS)



	
