all: bin/flatter 
SRC_FLATTER := flatter/main.cpp \
	mmo/mmo_class.cpp \
	util/table.cpp \
	util/type.cpp  \
	util/debug.cpp  \
	flatter/class_finder.cpp \
	flatter/remove_composition.cpp \
	util/ast_visitors/constant_expression.cpp \
    util/ast_visitors/contains_expression.cpp \
	util/ast_visitors/dot_expression.cpp \
	util/ast_visitors/eval_expression.cpp \
	util/ast_visitors/eval_expression_flatter.cpp \
	util/ast_visitors/mark_connector.cpp \
	util/ast_visitors/partial_eval_expression.cpp \
	util/ast_visitors/replace_expression.cpp \
    util/graph/graph_definition.cpp \
	flatter/flatter.cpp \
	flatter/connectors.cpp \
	mmo/mmo_tree.cpp


OBJS_FLATTER= $(SRC_FLATTER:.cpp=.o)
-include $(patsubst %,$(DEPDIR)/%.d,$(basename $(SRC_FLATTER)))

bin/flatter: $(OBJS_FLATTER) $(LIBMODELICA)
	$(CXX) $(CXXFLAGS) -o bin/flatter $(OBJS_FLATTER) -L./lib -lmodelica



	
