CAUSALIZE2FLAGS = -DENABLE_DEBUG_MSG
OBJS_CAUSALIZE2 := $(OBJS_COMMON) \
            causalize/graph_implementation/causalize2/main.o \
            mmo/mmo_class.o \
            util/ast_util.o \
            util/type.o \
            util/type_check.o \
            util/symbol_table.o \
            util/debug.o \
			causalize/graph_implementation/causalize2/graph_builder.o \
			causalize/graph_implementation/causalize2/occurrence_checker.o\
			causalize/graph_implementation/causalize2/graph_printer.o\
			causalize/graph_implementation/causalize2/causalization_algorithm.o\
            causalize/graph_implementation/compref_occurrence.o \
			causalize/graph_implementation/for_unrolling/for_index_iterator.o\
            util/solve.o \
            util/ginac_interface.o \
            causalize/graph_implementation/state_variables_finder.o \
            causalize/graph_implementation/unknowns_collector.o \
			causalize/graph_implementation/causalization_strategy.o\
            causalize/graph_implementation/cycles_identification_strategy.o \
            causalize/graph_implementation/for_unrolling/process_for_equations.o

LIB_CAUSALIZE = -lginac


bin/causalize2: $(OBJS_CAUSALIZE2)
	$(CXX) $(CXXFLAGS) -o bin/causalize2 $(OBJS_CAUSALIZE2) $(LIB_CAUSALIZE)


