# The Directories, Source, Includes, Objects, Binary 
CAUSALIZE_SBG_DIR  := $(CAUSALIZE_DIR)/sbg_implementation
CAUSALIZE_SBG      := bin/causalize
CAUSALIZE_SBG_TEST := test-causalize

all: $(CAUSALIZE_SBG)

# Sources
CAUSALIZE_SBG_SRC := \
    $(CAUSALIZE_SBG_DIR)/main.cpp \
    $(CAUSALIZE_SBG_DIR)/algebraic_loops_detection.cpp \
    $(CAUSALIZE_SBG_DIR)/equation_info.cpp \
    $(CAUSALIZE_SBG_DIR)/generate_sbg_input.cpp \
    $(CAUSALIZE_SBG_DIR)/horizontal_sorting.cpp \
    $(CAUSALIZE_SBG_DIR)/set_vertex.cpp \
    $(CAUSALIZE_SBG_DIR)/set_edge.cpp \
    $(CAUSALIZE_SBG_DIR)/tearing.cpp \
    $(CAUSALIZE_SBG_DIR)/vertical_sorting.cpp \
	$(CAUSALIZE_SBG_DIR)/tearing_variables.cpp \
	$(UTIL_DIR)/affine_transformation.cpp \
	$(UTIL_DIR)/affine_diag_transformation.cpp \
	$(UTIL_DIR)/compact_set.cpp \
	$(UTIL_DIR)/translation.cpp \
	$(UTIL_DIR)/ast_visitors/affine_expr_visitor.cpp \
	$(UTIL_DIR)/ast_visitors/compact_set_visitor.cpp \
	$(UTIL_DIR)/ast_visitors/constant_expression.cpp \
	$(UTIL_DIR)/ast_visitors/replace_equation.cpp \
	$(UTIL_DIR)/ast_visitors/matching_exps.cpp \
	$(UTIL_DIR)/affine_expr.cpp \
	$(UTIL_DIR)/logger.cpp

# Objects
CAUSALIZE_SBG_OBJ=$(addprefix $(BUILD_DIR)/, $(CAUSALIZE_SBG_SRC:.cpp=.o))

$(BUILD_DIR)/$(CAUSALIZE_SBG_DIR)/%.o : $(CAUSALIZE_SBG_DIR)/%.cpp
	$(CC) $(INCLUDES) $(BOOST_1_81_INC) $(SBG_LIB_DEV_INCLUDE) $(CXXFLAGS) -MM -MT $@ -MF $(patsubst %.o,%.d,$@) $<
	$(CC) $(INCLUDES) $(BOOST_1_81_INC) $(SBG_LIB_DEV_INCLUDE) -c $< -o $@ $(CXXFLAGS)

create-folders::
	@mkdir -p $(BUILD_DIR)/$(CAUSALIZE_DIR)/sbg_implementation

$(CAUSALIZE_SBG): $(CAUSALIZE_SBG_OBJ) $(CAUSALIZE_COMMON_OBJ) $(LIBMODELICA)
	$(CXX) $(CXXFLAGS) $(INCLUDES) $(SBG_LIB_DEV_INCLUDE) -o $(CAUSALIZE_SBG) $(CAUSALIZE_COMMON_OBJ) $(CAUSALIZE_SBG_OBJ) $(SBG_LIB_DEV_LINK) $(LIBS)

# Disable the tests until we have the binary/API interface working.
$(CAUSALIZE_SBG_TEST):
	@echo BUILDING CAUSALIZE TESTS
#	@cd causalize/sbg_implementation/test && $(MAKE) bin/test-causalize 
	@echo Done
	@echo RUNNING CAUSALIZE TESTS
#	@cd causalize/sbg_implementation/test && $(MAKE) test-causalize 
	@echo Done
