all: bin/grp_causalize 
SRC_GRP_CAUSALIZE := \
                  causalize/graph_implementation/main.cpp \
                  causalize/graph_implementation/apply_tarjan.cpp \
                  causalize/graph_implementation/unknowns_collector.cpp \
                  causalize/graph_implementation/causalization_strategy.cpp \
                  causalize/graph_implementation/vector/contains_vector.cpp \
                  causalize/graph_implementation/vector/graph_builder.cpp \
                  causalize/graph_implementation/vector/causalization_algorithm.cpp \
                  causalize/graph_implementation/vector/splitfor.cpp \
                  causalize/graph_implementation/graph/graph_definition.cpp \
                  causalize/common/for_unrolling/process_for_equations.cpp \

OBJS_GRP_CAUSALIZE = $(SRC_GRP_CAUSALIZE:.cpp=.o)
-include $(patsubst %,$(DEPDIR)/%.d,$(basename $(SRC_GRP_CAUSALIZE)))
LIB_CAUSALIZE = -L./lib -lmodelica -lginac

bin/grp_causalize: $(OBJS_GRP_CAUSALIZE) $(OBJS_COMMON_CAUSALIZE) lib/libmodelica.a
	$(CXX) $(CXXFLAGS) -o bin/grp_causalize $(OBJS_COMMON_CAUSALIZE) $(OBJS_GRP_CAUSALIZE) $(LIB_CAUSALIZE)
